### ISSUE TITLE
Error no available connectionString

### ISSUE THREAD

**Issue by TobeyQin** [microsoft/openpaimarketplace#104] opened 2020-11-20 09:10 UTC
## Reproduction step:

1. In the Marketplace List page, click any template.
2. click "use" button, and then show below error:

![image](https://user-images.githubusercontent.com/32830091/99781018-4501f180-2b52-11eb-9037-38df327b2089.png)

## Root cause:
Empty Connection String when initializing the marketplace.

## Hotfix
Add a certain connection string when initialization.

## Long term solution
\<TBD>

**Comment by debuggy** [comment] 2020-11-27 05:33
This is caused by database initialization, and could be fixed by manually post a blob storage connection string.

**Closed by debuggy** 2020-11-27 05:33 UTC
